### /api/v1/auth/signin
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "adrian.toral@live.u-tad.com",
  "password": "Adriantoral@12345"
}

> {%
    client.global.set("auth_token", response.body.data);
%}

### /api/v1/auth/signup
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "correo": "adrian.toral@live.u-tad.com",
  "alias": "adriantoral",
  "nombre_completo": "Adrian Toral",
  "password": "Adriantoral@12345",
  "frase_recuperacion": "adriantoral",
  "descripcion": "None",
  "portfolio": "None",
  "foto": "None",
  "rol": "alumno",
  "promocion": 2019
}

### /api/v1/auth/signup/validate
GET http://localhost:3000/api/v1/auth/signup/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYWNoZV9rZXkiOiJwZW5kaW5nOmFkcmlhbi50b3JhbEBsaXZlLnUtdGFkLmNvbSIsImlhdCI6MTcxMDUzODY2NywiZXhwIjoxNzEwNTQwNDY3fQ.Z-vARy2FFs9a_2NCTY4OXRqKHYj7L1dd_0KbF-M_QI0

### /api/v1/auth/me
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{auth_token}}

### /api/v1/auth/recover
POST http://localhost:3000/api/v1/auth/recover
Content-Type: application/json

{
  "correo": "adrian.toral@live.u-tad.com"
}
