### /api/v1/auth/signin
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "admin.admin@u-tad.com",
  "password": "Adriantoral@12345"
}

> {%
    client.global.set("auth_token", response.body.data);
%}

### /api/v1/proyectos/
GET http://localhost:3000/api/v1/proyectos/
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/me
GET http://localhost:3000/api/v1/proyectos/me
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos?filtros
GET http://localhost:3000/api/v1/proyectos?premiado=true&anio=2021&titulaciones=1,2,3&busqueda=miproyecto
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/subir
POST http://localhost:3000/api/v1/proyectos/subir
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="url"; filename="url.zip"
Content-Type: application/zip

< auth.http
--WebAppBoundary
Content-Disposition: form-data; name="portada"; filename="imagen.jpg"
Content-Type: image/jpeg

< auth.http
--WebAppBoundary

### /api/v1/proyectos/
POST http://localhost:3000/api/v1/proyectos/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "titulo": "Mi primer proyecto",
  "ficha": "Mi primer proyecto es una aplicación web que...",
  "url": "la url que devuleve la peticion de arriba o donde este guardado",
  "portada": "url de la imagen que devuelve la peticion de arriba o donde este guardado",
  "anio": 2021,
  "premiado": true,
  "participantes": [
    "correo1@gmail.com",
    "..."
  ],
  "asignaturas": [
    1,
    2,
    3
  ],
  "premios": [
    "Premio 1",
    "..."
  ]
}

### /api/v1/proyectos/1
GET http://localhost:3000/api/v1/proyectos/1
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/1
PATCH http://localhost:3000/api/v1/proyectos/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "ficha": "Mi primer proyecto es una aplicación web que PATCH",
  "participantes": [
    "patch@gmail.com"
  ],
  "asignaturas": [
    6
  ],
  "premios": [
    "Premio 1 Patch"
  ]
}

### /api/v1/proyectos/1
DELETE http://localhost:3000/api/v1/proyectos/1
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/1/aceptar
GET http://localhost:3000/api/v1/proyectos/1/aceptar
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/1/rechazar
GET http://localhost:3000/api/v1/proyectos/1/rechazar
Authorization: Bearer {{auth_token}}
