### /api/v1/auth/signin
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "adriantoral@live.u-tad.com",
  "password": "12345"
}

> {%
    client.global.set("auth_token", response.body.data.token);
%}

### /api/v1/auth/signin - FAIL
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "adriantoral@live.u-tad.com",
  "password": "123456"
}

### /api/v1/auth/signup
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "correo": "adriantoral@live.u-tad.com",
  "nombre_completo": "Adrian Toral",
  "alias": "adriantoral",
  "password": "12345",
  "frase_recuperacion": "adriantoral"
}

### /api/v1/auth/me
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{auth_token}}

### /api/v1/auth/me - FAIl
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer xx{{auth_token}}xx

### /api/v1/premios/
GET http://localhost:3000/api/v1/premios/
Authorization: Bearer {{auth_token}}

### /api/v1/premios/
POST http://localhost:3000/api/v1/premios/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "titulo": "Premio 1"
}

### /api/v1/premios/1
GET http://localhost:3000/api/v1/premios/1
Authorization: Bearer {{auth_token}}

### /api/v1/premios/1
PUT http://localhost:3000/api/v1/premios/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "titulo": "Premio 1 mejorado"
}

### /api/v1/premios/1
DELETE http://localhost:3000/api/v1/premios/1
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/
GET http://localhost:3000/api/v1/proyectos/
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/
POST http://localhost:3000/api/v1/proyectos/
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="ruta_fichero"; filename="package.json"
Content-Type: application/pdf

< package.json
--WebAppBoundary
Content-Disposition: form-data; name="id_creador"

1
--WebAppBoundary
Content-Disposition: form-data; name="titulo"

proyecto.titulo
--WebAppBoundary
Content-Disposition: form-data; name="ficha_tecnica"

proyecto.ficha_tecnica
--WebAppBoundary
Content-Disposition: form-data; name="ruta_imagen"; filename="imagen.jpg"
Content-Type: image/jpeg

< imagen.jpg
--WebAppBoundary

### /api/v1/proyectos/1
GET http://localhost:3000/api/v1/proyectos/1
Authorization: Bearer {{auth_token}}

### /api/v1/proyectos/1
PUT http://localhost:3000/api/v1/proyectos/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "titulo": "proyecto.titulo mejorado"
}

### /api/v1/proyectos/1
DELETE http://localhost:3000/api/v1/proyectos/1
Authorization: Bearer {{auth_token}}
